// Home
export const FETCH_BHOME_LIST='FETCH_BHOME_LIST'
export const FETCH_CHOME_LIST='FETCH_CHOME_LIST'

// book
export const FETCH_BOOK_LIST='FETCH_BOOK_LIST'
export const FETCH_NOVEL_LIST='FETCH_NOVEL_LIST'
export const FETCH_IT_LIST='FETCH_IT_LIST'
export const FETCH_NEW_LIST='FETCH_NEW_LIST'
export const FETCH_BOOK_DETAIL='FETCH_BOOK_DETAIL'
export const FETCH_BOOK_FIND='FETCH_BOOK_FIND'

// cd/lp
export const FETCH_CDLP_LIST='FETCH_CDLP_LIST'
export const FETCH_CLASSIC_LIST='FETCH_CLASSIC_LIST'
export const FETCH_CDLP_DETAIL='FETCH_CDLP_DETAIL'

// Board
export const FETCH_BOARD_LIST='FETCH_BOARD_LIST'
export const FETCH_BOARD_INSERT='FETCH_BOARD_INSERT'
export const FETCH_BOARD_DETAIL='FETCH_BOARD_DETAIL'
export const FETCH_BOARD_UPDATE='FETCH_BOARD_UPDATE'
export const FETCH_BOARD_UPDATE_DATA='FETCH_BOARD_UPDATE_DATA'
export const FETCH_BOARD_DELETE='FETCH_BOARD_DELETE'